"""
Shared LiteLLM proxy settings block.

Single source of truth for the static portion of
``volumes/litellm/config.yaml``. Two writers consume it:

  • ``bootstrapper/utils/litellm_config_generator.py`` writes a stub
    on the host (model_list empty) so the bind mount has a file.
  • ``services/litellm/init/scripts/init.py`` writes the real config from
    the YAML model catalogs + env (via ``model_resolver``) inside the init
    container, importing this module via the ``/catalog`` bind mount.

Keeping both writers in lockstep avoids silent drift if one is updated
without the other.
"""

from __future__ import annotations

from typing import Any, Dict, Mapping


#: Response-cache lifetime when the operator sets nothing. One hour is long
#: enough for a repeated prompt to actually hit, and short enough that a
#: changed model or catalog stops being served stale within a working
#: session. LiteLLM's own fallback is 60s, which almost never pays off.
DEFAULT_CACHE_TTL_SECONDS = 3600


def _cache_ttl(env: Mapping[str, str]) -> int:
    """Resolve ``LITELLM_CACHE_TTL`` (seconds) with a safe fallback.

    A non-numeric or negative value falls back to the default rather than
    failing the render: an unparseable tuning knob must never be able to
    stop the gateway from starting.
    """
    raw = (env.get("LITELLM_CACHE_TTL") or "").strip()
    if not raw:
        return DEFAULT_CACHE_TTL_SECONDS
    try:
        ttl = int(raw)
    except ValueError:
        return DEFAULT_CACHE_TTL_SECONDS
    return ttl if ttl > 0 else DEFAULT_CACHE_TTL_SECONDS


def base_settings(env: Mapping[str, str] | None = None) -> Dict[str, Any]:
    """Return the LiteLLM ``litellm_settings`` / ``router_settings`` /
    ``general_settings`` dict. Caller adds ``model_list`` separately.

    All values that LiteLLM resolves at proxy-start use the
    ``os.environ/...`` form so they're read from the LiteLLM
    container's environment, not baked into the YAML at render time.
    """
    values = env or {}
    source = values.get("LANGFUSE_SOURCE", "").strip().lower()
    litellm_settings: Dict[str, Any] = {
        "cache": True,
        "cache_params": {
            "type": "redis",
            "host": "os.environ/REDIS_HOST",
            "port": "os.environ/REDIS_PORT",
            "password": "os.environ/REDIS_PASSWORD",
            # ttl and namespace are baked as literals rather than
            # ``os.environ/...``: LiteLLM resolves that form to a STRING, and
            # ttl must be a number. The config is regenerated by litellm-init
            # on every startup, so a literal is still operator-configurable.
            #
            # Without an explicit ttl LiteLLM falls back to BaseCache's
            # ``default_ttl = 60`` — technically bounded, but 60s is far too
            # short for a response cache to pay for itself on anything but
            # rapid-fire identical prompts.
            "ttl": _cache_ttl(values),
            # Redis db 0 is shared with n8n's BullMQ queue, Kong's rate-limit
            # counters, Langfuse's queue and the backend's media store (see
            # services/redis/README.md). A namespace keeps gateway cache keys
            # identifiable, so they can be scanned or dropped without touching
            # a neighbour's keyspace.
            "namespace": (values.get("LITELLM_CACHE_NAMESPACE") or "litellm.cache").strip(),
        },
        "drop_params": True,
        # Prometheus metrics — emits per-model request/token/cost/latency
        # series on /metrics (same port as the proxy, 4000). Scraped by
        # the observability bundle's Prometheus when PROMETHEUS_SOURCE=container.
        # When disabled, the callback still loads but its emissions just sit
        # idle — no consumer hits /metrics. Harmless overhead.
        "callbacks": ["prometheus"],
    }
    if source == "container":
        litellm_settings["success_callback"] = ["langfuse"]

    return {
        "litellm_settings": litellm_settings,
        "router_settings": {
            "redis_host": "os.environ/REDIS_HOST",
            "redis_port": "os.environ/REDIS_PORT",
            "redis_password": "os.environ/REDIS_PASSWORD",
        },
        "general_settings": {
            "master_key": "os.environ/LITELLM_MASTER_KEY",
            "database_url": "os.environ/DATABASE_URL",
            "store_model_in_db": True,
        },
    }
