#!/usr/bin/env python3
"""Refresh or verify Local Deep Researcher's combined runtime lock."""

from __future__ import annotations

import argparse
import difflib
import hashlib
from pathlib import Path
import shutil
import tempfile

try:
    import tomllib
except ModuleNotFoundError:  # Python 3.10
    import tomli as tomllib

import yaml

try:
    from scripts.bounded_subprocess import (
        CommandTimedOut,
        DEFAULT_TIMEOUT_SECONDS,
        redacted_failure,
        run_bounded,
    )
except ModuleNotFoundError:  # Direct ``python scripts/...`` invocation.
    from bounded_subprocess import (  # type: ignore[no-redef]
        CommandTimedOut,
        DEFAULT_TIMEOUT_SECONDS,
        redacted_failure,
        run_bounded,
    )


ROOT = Path(__file__).resolve().parents[1]
SERVICE = ROOT / "services/local-deep-researcher"
MANIFEST = SERVICE / "service.yml"
LOCK_INPUTS = SERVICE / "locks"
RUNTIME_PYPROJECT = LOCK_INPUTS / "runtime-pyproject.toml"
RUNTIME_UV_LOCK = LOCK_INPUTS / "runtime.uv.lock"
RUNTIME_REQUIREMENTS = SERVICE / "build/config/runtime-requirements.lock"
UPSTREAM_URL = "https://github.com/langchain-ai/local-deep-researcher.git"
BUILD_DEPENDENCIES = ("setuptools==83.0.0", "wheel==0.47.0")
SECURITY_DEPENDENCIES = (
    "click>=8.3.3",
    "langchain-classic>=1.0.7",
    "langsmith>=0.8.18",
    "soupsieve>=2.8.4",
)


def _run(*args: str, cwd: Path | None = None, quiet: bool = False) -> None:
    del quiet
    label = f"Local Deep Researcher {args[0]} command"
    try:
        result = run_bounded(
            args,
            cwd=cwd,
            timeout_seconds=DEFAULT_TIMEOUT_SECONDS,
        )
    except CommandTimedOut as exc:
        raise SystemExit(
            f"{label} timed out after {DEFAULT_TIMEOUT_SECONDS} seconds"
        ) from exc
    if result.returncode != 0:
        raise SystemExit(redacted_failure(label, result.returncode))


def _pins() -> tuple[str, str, str]:
    manifest = yaml.safe_load(MANIFEST.read_text(encoding="utf-8"))
    env = {
        entry["name"]: str(entry["default"])
        for entry in manifest["env"]
        if "default" in entry
    }
    return (
        env["LOCAL_DEEP_RESEARCHER_REF"],
        env["LOCAL_DEEP_RESEARCHER_UPSTREAM_LOCK_SHA256"],
        env["LOCAL_DEEP_RESEARCHER_LANGGRAPH_CLI_VERSION"],
    )


def _validate_combined_project(pyproject: Path, cli_version: str) -> None:
    project = tomllib.loads(pyproject.read_text(encoding="utf-8"))["project"]
    dependencies = set(project["dependencies"])
    required = {
        f"langgraph-cli[inmem]=={cli_version}",
        *BUILD_DEPENDENCIES,
        *SECURITY_DEPENDENCIES,
    }
    missing = required - dependencies
    if missing:
        raise SystemExit(f"combined lock project is missing exact pins: {sorted(missing)}")


def _stable_export(project_dir: Path, ref: str, lock_sha: str, cli: str) -> str:
    _validate_combined_project(project_dir / "pyproject.toml", cli)
    output = project_dir / "runtime-requirements.raw"
    _run(
        "uv",
        "export",
        "--project",
        str(project_dir),
        "--frozen",
        "--no-dev",
        "--no-emit-project",
        "--output-file",
        str(output),
        quiet=True,
    )
    lines = output.read_text(encoding="utf-8").splitlines(keepends=True)
    if lines and lines[0].startswith("# This file was autogenerated by uv"):
        lines = lines[2:]
    while lines and not lines[0].strip():
        lines.pop(0)
    header = (
        "# Generated from the manifest-pinned upstream uv.lock plus the exact\n"
        "# langgraph-cli[inmem], security floors, setuptools, and wheel versions documented in the service README.\n"
        f"# upstream-ref: {ref}\n"
        f"# upstream-lock-sha256: {lock_sha}\n"
        f"# langgraph-cli-version: {cli}\n"
    )
    return header + "".join(lines)


def _atomic_write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_suffix(path.suffix + ".tmp")
    temporary.write_text(content, encoding="utf-8")
    temporary.replace(path)


def refresh() -> None:
    ref, lock_sha, cli = _pins()
    with tempfile.TemporaryDirectory(prefix="atlas-ldr-lock-") as raw_tmp:
        source = Path(raw_tmp) / "source"
        _run("git", "clone", "-q", UPSTREAM_URL, str(source))
        _run("git", "checkout", "-q", "--detach", ref, cwd=source)
        actual_sha = hashlib.sha256((source / "uv.lock").read_bytes()).hexdigest()
        if actual_sha != lock_sha:
            raise SystemExit(
                f"upstream uv.lock digest mismatch: manifest={lock_sha}, actual={actual_sha}"
            )
        _run(
            "uv",
            "add",
            "--project",
            str(source),
            "--no-sync",
            f"langgraph-cli[inmem]=={cli}",
            *BUILD_DEPENDENCIES,
            *SECURITY_DEPENDENCIES,
        )
        _validate_combined_project(source / "pyproject.toml", cli)
        LOCK_INPUTS.mkdir(parents=True, exist_ok=True)
        shutil.copy2(source / "pyproject.toml", RUNTIME_PYPROJECT)
        shutil.copy2(source / "uv.lock", RUNTIME_UV_LOCK)
        _atomic_write(
            RUNTIME_REQUIREMENTS,
            _stable_export(source, ref, lock_sha, cli),
        )
    print("Wrote Local Deep Researcher combined lock inputs and runtime requirements")


def check() -> None:
    ref, lock_sha, cli = _pins()
    with tempfile.TemporaryDirectory(prefix="atlas-ldr-lock-check-") as raw_tmp:
        project = Path(raw_tmp)
        shutil.copy2(RUNTIME_PYPROJECT, project / "pyproject.toml")
        shutil.copy2(RUNTIME_UV_LOCK, project / "uv.lock")
        expected = _stable_export(project, ref, lock_sha, cli)
    actual = RUNTIME_REQUIREMENTS.read_text(encoding="utf-8")
    if actual != expected:
        diff = "".join(
            difflib.unified_diff(
                actual.splitlines(keepends=True),
                expected.splitlines(keepends=True),
                fromfile=str(RUNTIME_REQUIREMENTS),
                tofile="regenerated runtime requirements",
            )
        )
        raise SystemExit(
            "Local Deep Researcher runtime lock drift; regenerate the committed "
            f"lock inputs and requirements:\n{diff}"
        )
    print("PASS Local Deep Researcher runtime lock byte-equivalence")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="verify without writing")
    args = parser.parse_args()
    check() if args.check else refresh()


if __name__ == "__main__":
    main()
