"""The security policy is a published page on every documentation surface (#1047)."""

from __future__ import annotations

import re
from pathlib import Path

import yaml

from scripts.docs.build_docs import render_mkdocs_yml
from scripts.docs.manifest import load_manifest
from tests.three_surface_test_utils import (
    PROJECTION_ROOT,
    ensure_generated_docs,
    surface_text,
)


ROOT = Path(__file__).resolve().parents[2]
POLICY_SOURCE = "SECURITY.md"
REPORTING_HEADING = "Reporting a Vulnerability"


def _policy_page_manifest():
    return load_manifest(ROOT / "docs" / "manifest.yaml", ROOT)


def _policy_page():
    manifest = _policy_page_manifest()
    pages = [page for page in manifest.pages if page.source == POLICY_SOURCE]
    assert len(pages) == 1, "SECURITY.md must be declared exactly once in docs/manifest.yaml"
    return pages[0]


def test_security_policy_is_a_manifest_page_with_stable_routes() -> None:
    page = _policy_page()

    assert page.id == "security-policy"
    assert page.site_path.as_posix() == "security-policy.md"
    assert page.wiki_path.as_posix() == f"{page.number}-Security-Policy.md"


def test_security_policy_h1_carries_its_manifest_number() -> None:
    page = _policy_page()
    text = (ROOT / POLICY_SOURCE).read_text(encoding="utf-8")

    assert text.startswith(f"# {page.number}. Security Policy\n")


def test_security_policy_renders_actionable_content_on_site_and_wiki() -> None:
    """Every surface carries the reporting route itself, not just a title."""
    ensure_generated_docs()
    canonical = (ROOT / POLICY_SOURCE).read_text(encoding="utf-8")
    for surface in ("site", "wiki"):
        rendered = surface_text(POLICY_SOURCE, surface)
        assert REPORTING_HEADING in rendered, surface
        assert "Report a" in rendered and "vulnerability" in rendered, surface
        assert "Do not file public issues" in rendered, surface
    assert REPORTING_HEADING in canonical


def test_documentation_map_links_the_policy_instead_of_stripping_it() -> None:
    """The nonmanifest transform used to turn the map's link into plain text."""
    ensure_generated_docs()
    page = _policy_page()
    site_map = surface_text("docs/README.md", "site")
    wiki_map = surface_text("docs/README.md", "wiki")

    assert re.search(r"\[Security policy\]\(security-policy\.md\)", site_map)
    assert f"[Security policy]({page.wiki_path.stem})" in wiki_map
    assert "SECURITY.md" not in site_map and "SECURITY.md" not in wiki_map


def test_security_policy_is_reachable_in_site_nav_and_wiki_sidebar() -> None:
    ensure_generated_docs()
    page = _policy_page()
    # mkdocs.yml is gitignored and regenerated by the build, so render it
    # from the manifest rather than reading a file a fresh checkout lacks.
    mkdocs = yaml.safe_load(render_mkdocs_yml(_policy_page_manifest()))
    sidebar = (PROJECTION_ROOT / "wiki" / "_Sidebar.md").read_text(encoding="utf-8")

    assert "security-policy.md" in yaml.dump(mkdocs["nav"])
    assert f"]({page.wiki_path.stem})" in sidebar


def test_policy_changes_trigger_the_documentation_publication_workflow() -> None:
    workflow = yaml.safe_load(
        (ROOT / ".github" / "workflows" / "docs-pages.yml").read_text(encoding="utf-8")
    )
    paths = workflow[True]["push"]["paths"] if True in workflow else workflow["on"]["push"]["paths"]

    assert POLICY_SOURCE in paths


def test_policy_scan_wording_names_the_live_gate_jobs() -> None:
    """The policy must describe the scanning gates as they actually run (#1002)."""
    policy = (ROOT / POLICY_SOURCE).read_text(encoding="utf-8")
    workflow = (ROOT / ".github" / "workflows" / "services-lint.yml").read_text(encoding="utf-8")
    for job_name in (
        "Build-validation (Dockerfile + requirements.txt installability)",
        "Final-image scan (local Compose and init images)",
    ):
        assert f"name: {job_name}" in workflow, job_name
        assert job_name in policy, job_name
    assert ".trivyignore.yaml" in policy
    assert "not yet a required check" in policy
