"""The security policy (#1047) and the contribution guide (#1188) are root
files that are also published pages on every documentation surface."""

from __future__ import annotations

import functools
import re
from pathlib import Path
from typing import NamedTuple

import pytest
import yaml

from scripts.docs.build_docs import render_mkdocs_yml
from scripts.docs.manifest import load_manifest
from tests.three_surface_test_utils import (
    PROJECTION_ROOT,
    ensure_generated_docs,
    surface_text,
)


ROOT = Path(__file__).resolve().parents[2]
POLICY_SOURCE = "SECURITY.md"
REPORTING_HEADING = "Reporting a Vulnerability"

class RootPage(NamedTuple):
    source: str
    page_id: str
    title: str       # H1 after the manifest number
    site: str        # site path
    wiki: str        # wiki slug after the number
    link: str        # the documentation map's link text


ROOT_PAGES = [
    pytest.param(RootPage(POLICY_SOURCE, "security-policy", "Security Policy",
                          "security-policy.md", "Security-Policy", "Security policy"),
                 id="security-policy"),
    pytest.param(RootPage("CONTRIBUTING.md", "contributing", "Contributing",
                          "contributing.md", "Contributing", "Contributing guide"),
                 id="contributing"),
]


@functools.cache
def _manifest():
    return load_manifest(ROOT / "docs" / "manifest.yaml", ROOT)


def _root_page(source: str):
    manifest = _manifest()
    pages = [page for page in manifest.pages if page.source == source]
    assert len(pages) == 1, f"{source} must be declared exactly once in docs/manifest.yaml"
    return pages[0]


@pytest.mark.parametrize("root", ROOT_PAGES)
def test_root_page_is_a_manifest_page_with_stable_routes(root: RootPage) -> None:
    page = _root_page(root.source)

    assert page.id == root.page_id
    assert page.site_path.as_posix() == root.site
    assert page.wiki_path.as_posix() == f"{page.number}-{root.wiki}.md"


@pytest.mark.parametrize("root", ROOT_PAGES)
def test_root_page_h1_carries_its_manifest_number(root: RootPage) -> None:
    page = _root_page(root.source)
    text = (ROOT / root.source).read_text(encoding="utf-8")

    assert text.startswith(f"# {page.number}. {root.title}\n")


def test_security_policy_renders_actionable_content_on_site_and_wiki() -> None:
    """Every surface carries the reporting route itself, not just a title."""
    ensure_generated_docs()
    canonical = (ROOT / POLICY_SOURCE).read_text(encoding="utf-8")
    for surface in ("site", "wiki"):
        rendered = surface_text(POLICY_SOURCE, surface)
        assert REPORTING_HEADING in rendered, surface
        assert "Report a" in rendered and "vulnerability" in rendered, surface
        assert "Do not file public issues" in rendered, surface
    assert REPORTING_HEADING in canonical


@pytest.mark.parametrize("root", ROOT_PAGES)
def test_documentation_map_links_the_root_page_instead_of_stripping_it(root: RootPage) -> None:
    """The nonmanifest transform used to turn the map's link into plain text."""
    ensure_generated_docs()
    page = _root_page(root.source)
    site_map = surface_text("docs/README.md", "site")
    wiki_map = surface_text("docs/README.md", "wiki")

    assert re.search(rf"\[{re.escape(root.link)}\]\({re.escape(root.site)}\)", site_map)
    assert f"[{root.link}]({page.wiki_path.stem})" in wiki_map
    assert root.source not in site_map and root.source not in wiki_map


@pytest.mark.parametrize("root", ROOT_PAGES)
def test_root_page_is_reachable_in_site_nav_and_wiki_sidebar(root: RootPage) -> None:
    ensure_generated_docs()
    page = _root_page(root.source)
    # mkdocs.yml is gitignored and regenerated by the build, so render it
    # from the manifest rather than reading a file a fresh checkout lacks.
    mkdocs = yaml.safe_load(render_mkdocs_yml(_manifest()))
    sidebar = (PROJECTION_ROOT / "wiki" / "_Sidebar.md").read_text(encoding="utf-8")

    assert root.site in yaml.dump(mkdocs["nav"])
    assert f"]({page.wiki_path.stem})" in sidebar


@pytest.mark.parametrize("root", ROOT_PAGES)
def test_root_page_changes_trigger_the_documentation_publication_workflow(root: RootPage) -> None:
    workflow = yaml.safe_load(
        (ROOT / ".github" / "workflows" / "docs-pages.yml").read_text(encoding="utf-8")
    )
    paths = workflow[True]["push"]["paths"] if True in workflow else workflow["on"]["push"]["paths"]

    assert root.source in paths


def test_policy_scan_wording_names_the_live_gate_jobs() -> None:
    """The policy must describe the scanning gates as they actually run (#1002)."""
    policy = (ROOT / POLICY_SOURCE).read_text(encoding="utf-8")
    workflow = (ROOT / ".github" / "workflows" / "services-lint.yml").read_text(encoding="utf-8")
    for job_name in (
        "Build-validation (Dockerfile + requirements.txt installability)",
        "Final-image scan (local Compose and init images)",
    ):
        assert f"name: {job_name}" in workflow, job_name
        assert job_name in policy, job_name
    assert ".trivyignore.yaml" in policy
    assert "not yet a required check" in policy
